# services:
#   - type: web
#     name: amozn
#     env: python
#     plan: free
#     buildCommand: "./build.sh"
#     startCommand: "gunicorn myproject.wsgi:application"
#     routes:
#       - type: rewrite
#         source: "/(.*)"
#         destination: "/"


services:
  - type: web
    name: amozn
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn myproject.wsgi:application --bind 0.0.0.0:$PORT"
