# Generated by Django 5.2.8 on 2025-11-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_shorturl_long_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='long_url',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
