# Generated by Django 5.2.8 on 2025-11-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_shorturl_long_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonlink',
            name='product_url',
            field=models.URLField(),
        ),
    ]
