# Generated by Django 4.2.20 on 2026-06-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_amazonlink_product_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonlink',
            name='product_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='long_url',
            field=models.URLField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='short_code',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
