# Generated by Django 4.2.20 on 2026-06-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_amazonlink_product_url_alter_shorturl_long_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonlink',
            name='product_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='long_url',
            field=models.URLField(max_length=2000, unique=True),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='short_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
