# Generated by Django 4.2.20 on 2026-06-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_amazonlink_asin_product_availability_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant_images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
