# Generated by Django 4.2.20 on 2026-06-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_variant_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonlink',
            name='asin',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
