# Generated by Django 4.2.20 on 2026-06-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_amazonlink_asin'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='source',
            field=models.CharField(choices=[('amazon', 'Amazon'), ('flipkart', 'Flipkart'), ('myntra', 'Myntra'), ('ajio', 'Ajio')], db_index=True, default='amazon', max_length=20),
        ),
    ]
