# Generated by Django 4.2.20 on 2026-06-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_category_product_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonlink',
            name='tag',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
