# Generated by Django 4.2.20 on 2026-06-26 18:03

from django.db import migrations, models
import django.utils.timezone
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_amazonlink_product_url_alter_amazonlink_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.PositiveIntegerField(default=products.models._seed_views),
        ),
    ]
